export const data = [

    {
        question: "Which tag is used to create an ordered list in HTML?",
        option1: " <ul>",
        option2: "<ol>",
        option3: " <list>",
        option4: "<order>",
        ans: 1,
    },
    {
        question: "Which of the following is a semantic HTML tag?",
        option1: " <div>",
        option2: "<section>",
        option3: " <span>",
        option4: "<b>",
        ans: 2,
    },
    {
        question: "What is the default alignment of text in an HTML <p> tag?",
        option1: "left",
        option2: "center",
        option3: "right",
        option4: "justify",
        ans: 1,
    },
    {
        question: "Which HTML attribute is used to specify inline styles?",
        option1: "id",
        option2: "style",
        option3: "class",
        option4: "css",
        ans: 2,
    },
    {
        question: "Which CSS property is used to make text bold?",
        option1: "font-size",
        option2: "font-family",
        option3: "font-weight",
        option4: "text-size",
        ans: 3,
    },
    {
        question: "What does typeof null return in JavaScript?",
        option1: "undefined",
        option2: "object",
        option3: "null",
        option4: "boolean",
        ans: 2,
    },
    {
        question: "How do you declare a constant in JavaScript?",
        option1: "const myConst;",
        option2: "constant myConst;",
        option3: "const myConst = value;",
        option4: "var myConst = value;",
        ans: 3,
    },
    {
        question: "How do you apply a specific style to an HTML element with an ID?",
        option1: "#id",
        option2: ".id",
        option3: "*id",
        option4: "id:",
        ans: 1,
    },
    {
        question: "What does Array.push() do in JavaScript?",
        option1: "Adds an element to the beginning of an array",
        option2: "Removes the last element of an array",
        option3: "Adds an element to the end of an array",
        option4: "Removes the first element of an array",
        ans: 3,
    },
    {
        question: "What is the correct way to center a block element horizontally in CSS?",
        option1: "margin: auto;",
        option2: "text-align: center;",
        option3: "align: center;",
        option4: "padding: auto;",
        ans: 1,
    },
    {
        question: "What does the z-index property in CSS do?",
        option1: "Controls the visibility of an element",
        option2: "Specifies the stacking order of elements",
        option3: "Controls the zoom level of an element",
        option4: "Adjusts the width of an element",
        ans: 2,
    },
    {
        question: "What is JSX in React?",
        option1: "A tool for writing CSS",
        option2: " A syntax extension for JavaScript",
        option3: "A file format for React",
        option4: "A package manager",
        ans: 2,
    },
    {
        question: "Which command is used to create a new React app?",
        option1: "npm new react-app",
        option2: "npm start react",
        option3: "npx create-react-app",
        option4: "react-init",
        ans: 3,
    },
    {
        question: "What is React?",
        option1: "A database",
        option2: "A library for building user interfaces",
        option3: "A programming language",
        option4: "A framework for backend development",
        ans: 2,
    },
    {
        question: "Which of the following is not a JavaScript data type?",
        option1: "var myVar;",
        option2: "let myVar;",
        option3: "const myVar;",
        option4: "All of the above",
        ans: 4,
    },
]
